name: multirep_202203
channels:
  - defaults
  - conda-forge
dependencies:
  - blas=1.0
  - bottleneck=1.3.4
  - ca-certificates=2022.3.18
  - certifi=2021.10.8
  - future=0.18.2
  - h5py=3.6.0
  - hdf5=1.10.6
  - intel-openmp=2021.4.0
  - libcxx=12.0.0
  - libffi=3.3
  - libgfortran=3.0.0
  - make=4.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - numexpr=2.8.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openssl=1.1.1n
  - packaging=21.3
  - pandas=1.4.1
  - pip=21.2.4
  - pyparsing=3.0.4
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytz=2021.3
  - pyyaml=6.0
  - readline=8.1.2
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.2
  - tk=8.6.11
  - tzdata=2021e
  - uncertainties=3.1.6
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - pip:
    - num2tex==0.8
